import Image from "next/image";
import type { ReactNode } from "react";

const asset = (name: string) => "/figma/" + name;
function Art({name,className=""}:{name:string;className?:string}) {return <Image src={asset(name)} alt="" fill unoptimized loading={name === "imgDecorativeVector2.svg" || name === "imgHeroBackground.svg" ? "eager" : "lazy"} className={className} aria-hidden sizes="100vw"/>}
function Eyebrow({children}:{children:ReactNode}){return <span className="eyebrow">{children}</span>}
function Button({children,href,arrow=false}:{children:ReactNode;href:string;arrow?:boolean}){return <a className="button" href={href}>{children}{arrow&&<Image src={asset("imgFrame340.svg")} width={34} height={34} alt=""/>}</a>}
export function Header(){return <header className="hero" id="top">
  <Art name="imgHeroBackground.svg" className="hero-bg"/>
  <nav aria-label="Main navigation" className="navigation">
    <a href="#about">About us</a><a href="#services">Services</a>
    <a href="#top" aria-label="FLO Engineering home" className="nav-logo"><Image src={asset("imgCapa2.svg")} width={86} height={86} alt="FLO"/><span>ENGINEERING</span><Image className="logo-mark" src={asset("imgVector.svg")} width={15} height={15} alt=""/></a>
    <a href="#projects">Projects</a><a href="#contact">Contact Us</a>
  </nav>
  <div className="hero-content"><h1><span>Built on<br/>Integrity.</span><br/>Engineered<br/>to last.</h1><div className="hero-buttons"><Button href="#projects">Projects</Button><a href="#services" className="secondary-link">Services</a></div></div>
  <div className="hero-art"><Image src={asset("hero.png")} fill priority alt="A winding road through green mountain slopes" sizes="(max-width: 700px) 100vw, 56vw"/></div>
  <div className="hero-wave"><Art name="imgDecorativeWave.svg"/></div>
</header>}
export function About(){return <section id="about" className="about" aria-labelledby="about-title"><Art name="imgBackgroundImage2.svg" className="about-bg"/><div className="about-pattern"><Art name="imgDecorativeVector2.svg"/></div><h2 id="about-title">The partner<br/>communities rely on</h2><p>From road repair to landslide stabilization, we restore what needs attention today while reinforcing what needs to last tomorrow.</p><div className="gallery">{["imgGalleryImage01.png","imgGalleryImage02.png","imgGalleryImage03.png"].map((name,i)=><div key={name}><Image src={asset(name)} fill unoptimized sizes="(max-width:700px) 30vw, 24vw" alt={["Engineering team on a construction site","Earthmoving equipment at work","Mountain road surrounded by green hills"][i]}/></div>)}</div></section>}
const services=[{title:"Emergency Work",hoverTitle:"Emergency Work",description:"Rapid, precise infrastructure repair and restoration.",image:"imgServiceImage.png",hover:"1825355-imgImg87107.svg",pattern:"1825355-imgVector.svg"},{title:"Infrastructure planning",hoverTitle:"Strategic Infrastructure Planning",description:"Long-term infrastructure planning for stronger, more resilient communities.",image:"imgServiceImage1.png",hover:"1825340-imgImg87108.svg",pattern:"1825340-imgVector.svg"}];
export function Services(){return <section id="services" className="services section-pad" aria-labelledby="services-title"><Eyebrow>Our services</Eyebrow><h2 id="services-title">From emergency response to lasting resilience</h2><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.title}><Image src={asset(s.image)} fill sizes="(max-width:700px) 100vw, 55vw" alt={i===0?"Road repair crews and excavators":"Engineers planning infrastructure works"} className="service-photo"/><div className="service-hover-image"><Art name={s.hover}/></div><div className="service-decoration"><Image src={asset(s.pattern)} width={490} height={153} alt=""/><Image src={asset(s.pattern)} width={490} height={153} alt=""/></div><span className="service-number">0{i+1}</span><div className="service-copy"><h3><span className="service-title-default">{s.title}</span><span className="service-title-hover">{s.hoverTitle}</span></h3><p>{s.description}</p><Button href="#contact" arrow>Learn More</Button></div></article>)}</div></section>}
const stats=[["40","+","Years of experience","Decades of engineering and field experience.","imgCardBackground.svg"],["20","+","Projects completed","From small repairs to major infrastructure builds.","imgCardBackground1.svg"],["8","+","Public & Private Partnerships","Trusted by Public Agencies & Private Partners","imgCardBackground3.svg"],["100","%","On-time delivery","We finish what we start, when we say we will.","imgCardBackground2.svg"]];
export function Results(){return <section className="results" aria-labelledby="results-title"><Image src={asset("imgBackgroundImage1.png")} alt="FLO Engineering excavation team" fill sizes="100vw" className="results-photo"/><div className="results-shade"/><div className="results-heading"><h2 id="results-title">4 DECADES OF<br/>PROVEN RESULTS</h2><p>We&apos;ve earned our reputation through consistent work and accountability.</p></div><div className="stats">{stats.map(([number,suffix,title,description,bg],i)=><article className={"stat stat-"+i} key={title}><Art name={bg} className="stat-bg"/><div className="stat-content"><p className="stat-number">{number}<span>{suffix}</span></p><h3>{title}</h3><p className="stat-description">{description}</p></div></article>)}</div></section>}
const projects=[["I-10 Robertson Boulevard","Drainage & Roadway Restoration","imgCardImage.png"],["SR-27 Topanga Canyon","Emergency Landslide Response","imgCardImage1.png"],["SR-27 Topanga Canyon","Emergency Slope Stabilization","imgCardImage2.png"]];
export function Projects(){return <section id="projects" className="projects section-pad" aria-labelledby="projects-title"><Eyebrow>Recent projects</Eyebrow><h2 id="projects-title">Reliability when it matters most</h2><div className="project-grid">{projects.map(([title,description,img])=><article className="project-card" key={description}><div className="project-image"><Image src={asset(img)} fill sizes="(max-width:700px) 100vw, 33vw" alt={description}/></div><div className="project-body"><h3>{title}</h3><p>{description}</p><a className="project-link" href={"mailto:info@floengineering.net?subject="+encodeURIComponent(title+" — "+description)} aria-label={"View Project: "+title+" — "+description}><span className="button">View Project</span><Image src={asset("imgArrowIcon.svg")} width={34} height={34} alt=""/></a></div></article>)}</div></section>}
export function Testimonials(){return <section className="testimonials" aria-labelledby="testimonials-title"><div className="testimonial-pattern"><Art name="imgDecorativeVector1.svg"/></div><div className="testimonial-heading"><Eyebrow>Testimonials</Eyebrow><h2 id="testimonials-title">The partner communities rely on</h2></div><div className="testimonial-track" tabIndex={0} role="region" aria-label="Customer testimonials, scroll for more">{[0,1].map(i=><figure key={i} className="testimonial"><blockquote>&quot;They showed up before dawn and didn&apos;t leave until the slope was secure.&quot;</blockquote><figcaption><Image src={asset("imgAvatar.png")} width={68} height={54} alt="Marcus Chen"/><div><p>Marcus Chen</p><span>Facilities Director, Monterey Park</span></div></figcaption></figure>)}</div></section>}
export function Contact(){return <section id="contact" className="contact" aria-labelledby="contact-title"><Image src={asset("imgBackgroundImage.png")} fill sizes="100vw" alt="FLO engineer overseeing road construction"/><div className="contact-shade"/><div className="contact-copy"><h2 id="contact-title">Ready when it can’t wait</h2><Button href="mailto:info@floengineering.net">Contact Us</Button></div></section>}
const company=["About us","Services","Projects","Contact","Careers"];
const resources=["Blog","News","FAQ","Support","Documentation"];
const targets=["#about","#services","#projects","#contact","mailto:info@floengineering.net?subject=Careers"];
export function Footer(){return <footer className="footer"><div className="footer-pattern"><Art name="imgDecorativeVector.svg"/></div><div className="footer-top"><div className="footer-contact"><h2>Contact Us</h2><address>251 South Lake Avenue<br/>Suite 800<br/>Pasadena, CA<br/><br/><br/><a href="mailto:info@floengineering.net">info@floengineering.net</a><br/>License No. 1078272</address><div className="certifications"><Image src={asset("imgDbeCertification.png")} width={53} height={53} alt="DBE certification"/><div className="sbe"><Image src={asset("imgSbeCertification.png")} width={86} height={86} alt="SBE certification"/></div></div></div><div className="footer-links"><h2>Company</h2>{company.map((c,i)=><a key={c} href={targets[i]}>{c}</a>)}</div><div className="footer-links"><h2>Resources</h2>{resources.map(c=><a key={c} href={"mailto:info@floengineering.net?subject="+c}>{c}</a>)}</div><div className="socials">{["Instagram","LinkedIn","Youtube"].map(c=><Image key={c} src={asset("img"+c+".svg")} width={23} height={23} alt={c}/>)}</div></div><div className="footer-bottom"><a className="footer-logo" href="#top" aria-label="FLO Engineering, back to top"><Image src={asset("imgCapa1.svg")} width={390} height={182} alt="FLO"/><Image className="trademark" src={asset("imgTrademark.svg")} width={30} height={16} alt="Trademark"/></a><div className="terms">{["Privacy policy","Terms of service","Cookies settings"].map(t=><a key={t} href={"mailto:info@floengineering.net?subject="+encodeURIComponent(t)}>{t}</a>)}</div><p>© 2025 FLO Engineering. All rights reserved.</p></div></footer>}
